# Generated by Django 2.2.9 on 2019-12-30 00:02

import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('page_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('introduction', models.TextField(blank=True, help_text='Text to describe the page')),
                ('body', wagtail.core.fields.StreamField([('heading_block', wagtail.core.blocks.StructBlock(
                    [('heading_text', wagtail.core.blocks.CharBlock(classname='title', required=True)), ('size',
                                                                                                         wagtail.core.blocks.ChoiceBlock(
                                                                                                             blank=True,
                                                                                                             choices=[(
                                                                                                                      '',
                                                                                                                      'Select a header size'),
                                                                                                                      (
                                                                                                                      'h2',
                                                                                                                      'H2'),
                                                                                                                      (
                                                                                                                      'h3',
                                                                                                                      'H3'),
                                                                                                                      (
                                                                                                                      'h4',
                                                                                                                      'H4')],
                                                                                                             required=False))])),
                                                          ('paragraph_block',
                                                           wagtail.core.blocks.RichTextBlock(icon='doc-full',
                                                                                             template='blocks/paragraph_block.html')),
                                                          ('image_block', wagtail.core.blocks.StructBlock([('image',
                                                                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                                                                required=True)),
                                                                                                           ('caption',
                                                                                                            wagtail.core.blocks.CharBlock(
                                                                                                                required=False)),
                                                                                                           (
                                                                                                           'attribution',
                                                                                                           wagtail.core.blocks.CharBlock(
                                                                                                               required=False))])),
                                                          ('block_quote', wagtail.core.blocks.StructBlock(
                                                              [('text', wagtail.core.blocks.TextBlock()), (
                                                              'attribute_name',
                                                              wagtail.core.blocks.CharBlock(blank=True,
                                                                                            label='e.g. Mary Berry',
                                                                                            required=False))])), (
                                                          'embed_block', wagtail.embeds.blocks.EmbedBlock(
                                                              help_text='Insert an embed URL e.g https://www.youtube.com/embed/SGJFWirQ3ks',
                                                              icon='placeholder', template='blocks/embed_block.html'))],
                                                         blank=True, verbose_name='Page body')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                            to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
